[2024-01-03T14:46:05.410+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-03T14:45:00+00:00 [queued]>
[2024-01-03T14:46:05.417+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-03T14:45:00+00:00 [queued]>
[2024-01-03T14:46:05.417+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-03T14:46:05.429+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-01-03 14:45:00+00:00
[2024-01-03T14:46:05.434+0000] {standard_task_runner.py:57} INFO - Started process 625 to run task
[2024-01-03T14:46:05.438+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-01-03T14:45:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpj0d1rmtk']
[2024-01-03T14:46:05.440+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask predict_ntu_task
[2024-01-03T14:46:05.474+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-03T14:45:00+00:00 [running]> on host 93456042b127
[2024-01-03T14:46:05.536+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T14:45:00+00:00'
[2024-01-03T14:46:05.885+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-01-03T14:46:06.473+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-03T14:46:07.126+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-01-03T14:46:07.126+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 618ms/step
[2024-01-03T14:46:07.128+0000] {logging_mixin.py:150} INFO - new data : [[15.624476999999999], [15.157373000000002], [14.506058]]
[2024-01-03T14:46:07.128+0000] {logging_mixin.py:150} INFO - t+1 ntu : [12.965633]
[2024-01-03T14:46:07.128+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-01-03T14:46:07.132+0000] {python.py:183} INFO - Done. Returned value was: [12.965633]
[2024-01-03T14:46:07.149+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240103T144500, start_date=20240103T144605, end_date=20240103T144607
[2024-01-03T14:46:07.174+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-01-03T14:46:07.190+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
