[2024-02-04T15:22:07.578+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:21:00+00:00 [queued]>
[2024-02-04T15:22:07.586+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:21:00+00:00 [queued]>
[2024-02-04T15:22:07.586+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-04T15:22:07.598+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-02-04 15:21:00+00:00
[2024-02-04T15:22:07.604+0000] {standard_task_runner.py:57} INFO - Started process 2186 to run task
[2024-02-04T15:22:07.607+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-02-04T15:21:00+00:00', '--job-id', '982', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmp9w41gava']
[2024-02-04T15:22:07.609+0000] {standard_task_runner.py:85} INFO - Job 982: Subtask predict_ntu_task
[2024-02-04T15:22:07.643+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:21:00+00:00 [running]> on host 93456042b127
[2024-02-04T15:22:07.706+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T15:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T15:21:00+00:00'
[2024-02-04T15:22:08.046+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-02-04T15:22:08.642+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T15:22:09.319+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-02-04T15:22:09.319+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 643ms/step
[2024-02-04T15:22:09.320+0000] {logging_mixin.py:150} INFO - new data : [[9.411237], [11.037381], [12.89827]]
[2024-02-04T15:22:09.321+0000] {logging_mixin.py:150} INFO - t+1 ntu : [12.939011]
[2024-02-04T15:22:09.321+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-02-04T15:22:09.325+0000] {python.py:183} INFO - Done. Returned value was: [12.939011]
[2024-02-04T15:22:09.342+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240204T152100, start_date=20240204T152207, end_date=20240204T152209
[2024-02-04T15:22:09.386+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-04T15:22:09.402+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
