[2024-01-09T13:12:04.520+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:11:00+00:00 [queued]>
[2024-01-09T13:12:04.526+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:11:00+00:00 [queued]>
[2024-01-09T13:12:04.526+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-09T13:12:04.536+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-01-09 13:11:00+00:00
[2024-01-09T13:12:04.541+0000] {standard_task_runner.py:57} INFO - Started process 2148 to run task
[2024-01-09T13:12:04.544+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-01-09T13:11:00+00:00', '--job-id', '610', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmprm93itwe']
[2024-01-09T13:12:04.546+0000] {standard_task_runner.py:85} INFO - Job 610: Subtask predict_ntu_task
[2024-01-09T13:12:04.577+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:11:00+00:00 [running]> on host 93456042b127
[2024-01-09T13:12:04.635+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T13:11:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-09T13:11:00+00:00'
[2024-01-09T13:12:04.979+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-01-09T13:12:05.520+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-09T13:12:06.128+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-01-09T13:12:06.128+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 576ms/step
[2024-01-09T13:12:06.130+0000] {logging_mixin.py:150} INFO - new data : [[2.378079], [2.393498], [2.578674]]
[2024-01-09T13:12:06.130+0000] {logging_mixin.py:150} INFO - t+1 ntu : [1.784009]
[2024-01-09T13:12:06.130+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-01-09T13:12:06.134+0000] {python.py:183} INFO - Done. Returned value was: [1.784009]
[2024-01-09T13:12:06.150+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240109T131100, start_date=20240109T131204, end_date=20240109T131206
[2024-01-09T13:12:06.201+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-01-09T13:12:06.218+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
