[2024-02-04T14:46:06.750+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T14:45:00+00:00 [queued]>
[2024-02-04T14:46:06.757+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T14:45:00+00:00 [queued]>
[2024-02-04T14:46:06.757+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-04T14:46:06.773+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-02-04 14:45:00+00:00
[2024-02-04T14:46:06.779+0000] {standard_task_runner.py:57} INFO - Started process 641 to run task
[2024-02-04T14:46:06.782+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-02-04T14:45:00+00:00', '--job-id', '740', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpuhw01ytu']
[2024-02-04T14:46:06.784+0000] {standard_task_runner.py:85} INFO - Job 740: Subtask predict_ntu_task
[2024-02-04T14:46:06.817+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T14:45:00+00:00 [running]> on host 93456042b127
[2024-02-04T14:46:06.881+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T14:45:00+00:00'
[2024-02-04T14:46:07.221+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-02-04T14:46:07.821+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T14:46:08.474+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-02-04T14:46:08.475+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 618ms/step
[2024-02-04T14:46:08.476+0000] {logging_mixin.py:150} INFO - new data : [[3.677454], [3.7569980000000003], [3.7475199999999997]]
[2024-02-04T14:46:08.476+0000] {logging_mixin.py:150} INFO - t+1 ntu : [2.8725653]
[2024-02-04T14:46:08.476+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-02-04T14:46:08.480+0000] {python.py:183} INFO - Done. Returned value was: [2.8725653]
[2024-02-04T14:46:08.497+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240204T144500, start_date=20240204T144606, end_date=20240204T144608
[2024-02-04T14:46:08.522+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-04T14:46:08.538+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
