[2024-01-09T13:15:05.052+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:14:00+00:00 [queued]>
[2024-01-09T13:15:05.058+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:14:00+00:00 [queued]>
[2024-01-09T13:15:05.058+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-09T13:15:05.067+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-01-09 13:14:00+00:00
[2024-01-09T13:15:05.072+0000] {standard_task_runner.py:57} INFO - Started process 2679 to run task
[2024-01-09T13:15:05.074+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-01-09T13:14:00+00:00', '--job-id', '629', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmp0apbkxu2']
[2024-01-09T13:15:05.077+0000] {standard_task_runner.py:85} INFO - Job 629: Subtask predict_ntu_task
[2024-01-09T13:15:05.108+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-01-09T13:14:00+00:00 [running]> on host 93456042b127
[2024-01-09T13:15:05.171+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T13:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-09T13:14:00+00:00'
[2024-01-09T13:15:05.478+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-01-09T13:15:05.981+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-09T13:15:06.556+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-01-09T13:15:06.557+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 545ms/step
[2024-01-09T13:15:06.558+0000] {logging_mixin.py:150} INFO - new data : [[8.254125], [7.132115], [6.041308]]
[2024-01-09T13:15:06.559+0000] {logging_mixin.py:150} INFO - t+1 ntu : [4.362185]
[2024-01-09T13:15:06.559+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-01-09T13:15:06.562+0000] {python.py:183} INFO - Done. Returned value was: [4.362185]
[2024-01-09T13:15:06.577+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240109T131400, start_date=20240109T131505, end_date=20240109T131506
[2024-01-09T13:15:06.612+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-01-09T13:15:06.626+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
