[2024-02-04T15:17:06.013+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:16:00+00:00 [queued]>
[2024-02-04T15:17:06.020+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:16:00+00:00 [queued]>
[2024-02-04T15:17:06.021+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-04T15:17:06.031+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-02-04 15:16:00+00:00
[2024-02-04T15:17:06.038+0000] {standard_task_runner.py:57} INFO - Started process 1310 to run task
[2024-02-04T15:17:06.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-02-04T15:16:00+00:00', '--job-id', '949', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmp375qizep']
[2024-02-04T15:17:06.043+0000] {standard_task_runner.py:85} INFO - Job 949: Subtask predict_ntu_task
[2024-02-04T15:17:06.078+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T15:16:00+00:00 [running]> on host 93456042b127
[2024-02-04T15:17:06.142+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T15:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T15:16:00+00:00'
[2024-02-04T15:17:06.472+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-02-04T15:17:07.051+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T15:17:07.668+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-02-04T15:17:07.668+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 585ms/step
[2024-02-04T15:17:07.670+0000] {logging_mixin.py:150} INFO - new data : [[10.794069], [10.520867], [10.64623]]
[2024-02-04T15:17:07.670+0000] {logging_mixin.py:150} INFO - t+1 ntu : [9.459708]
[2024-02-04T15:17:07.670+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-02-04T15:17:07.674+0000] {python.py:183} INFO - Done. Returned value was: [9.459708]
[2024-02-04T15:17:07.690+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240204T151600, start_date=20240204T151706, end_date=20240204T151707
[2024-02-04T15:17:07.738+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-04T15:17:07.753+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
