[2024-02-04T16:26:06.519+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T16:25:00+00:00 [queued]>
[2024-02-04T16:26:06.526+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T16:25:00+00:00 [queued]>
[2024-02-04T16:26:06.526+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-04T16:26:06.537+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2024-02-04 16:25:00+00:00
[2024-02-04T16:26:06.543+0000] {standard_task_runner.py:57} INFO - Started process 5396 to run task
[2024-02-04T16:26:06.547+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'predict_ntu_task', 'scheduled__2024-02-04T16:25:00+00:00', '--job-id', '1401', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmp8wbwjz61']
[2024-02-04T16:26:06.550+0000] {standard_task_runner.py:85} INFO - Job 1401: Subtask predict_ntu_task
[2024-02-04T16:26:06.584+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.predict_ntu_task scheduled__2024-02-04T16:25:00+00:00 [running]> on host 93456042b127
[2024-02-04T16:26:06.648+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T16:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T16:25:00+00:00'
[2024-02-04T16:26:06.995+0000] {warnings.py:110} WARNING - /opt/***/dags/modeling.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lstm_df[col] = low_val

[2024-02-04T16:26:07.549+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T16:26:08.250+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2024-02-04T16:26:08.250+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 668ms/step
[2024-02-04T16:26:08.262+0000] {logging_mixin.py:150} INFO - new data : [[5.459454], [5.5907540000000004], [5.346095999999999]]
[2024-02-04T16:26:08.263+0000] {logging_mixin.py:150} INFO - t+1 ntu : [4.363566]
[2024-02-04T16:26:08.263+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2024-02-04T16:26:08.268+0000] {python.py:183} INFO - Done. Returned value was: [4.363566]
[2024-02-04T16:26:08.306+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=predict_ntu_task, execution_date=20240204T162500, start_date=20240204T162606, end_date=20240204T162608
[2024-02-04T16:26:08.364+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-04T16:26:08.382+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
